### ISSUE TITLE
403 Client Error: Forbidden for url - Microsoft-Azure-Application-Gateway

### ISSUE THREAD

**Issue by Cagataydemirkol** [StatisticsNZ/open-data-api#3]
Hi team,

**Followed example python api request "Example-Python-requests.md" as below.**

import stats_odata as odata

service = "https://api.stats.govt.nz/odata/v1"
endpoint = "EmploymentIndicators"
entity = ""
query_option = ""
api_key = 'xxxxxxxxxxxxxxxxxxxxx'
proxies = {}

ServiceEntities = odata.get_odata(service, endpoint, entity, query_option, api_key, proxies)

print(ServiceEntities)

**It returned**

403 Client Error: Forbidden for url: https://api.stats.govt.nz/odata/v1/EmploymentIndicators/
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>

0 Obs retrieved
Empty DataFrame
Columns: []
Index: []

**I have a valid account and api key, used VS Code on my local computer and an organisational cloud account which both of those failed. Wondering if you can trace back the logs to help me fix the issue?**

**Thank you!**

**Comment by MarkBroeksteeg** [comment]
Hello @Cagataydemirkol,

Its possible you need to specifiy a proxy server if you have one as this seems to be the only issue other users have raised.

**Comment by Cagataydemirkol** [comment]
Hi @MarkBroeksteeg,

I have confirmed with our technical team that requests are automatically proxied. Alternatively though, passing specific "User-Agent" in the headers as Postman solved the error.

However, I have noticed not all the datasources and their versions in InfoShare is available through API. Wondering if there is a release timeline on when we can expect to see more time series data becoming available?

Thanks!

**Comment by MarkBroeksteeg** [comment]
Good to hear you have resolved this issue.

The Open Data service is an experimental service that is likely to retire this year, so yes it only contains a small selection of datatsets mirrorred from our tools like http://infoshare.stats.govt.nz/ or https://nzdotstat.stats.govt.nz/wbos/Index.aspx

The replacement for the Open Data service will be an upgrade to our nz.stat data tool using the latest .Stat suite software https://siscc.org/stat-suite/. You can read more about this work here https://www.stats.govt.nz/tools/we-are-changing-our-data-tools/.
